name: Deploy Database

on:
  push:
    paths:
      - 'map_database/**'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy
      run: |
        cd ~/aiccmap_project/map_database && \
        git pull && \
        docker stop db_container || true && \
        docker rm db_container || true && \
        docker build -t db_image . && \
        docker run -d --name aicc_db_map -p 3306:3306 db_image && \
        docker stop redis_container || true && \
        docker rm redis_container || true && \
        docker run -d --name redis_container -p 6379:6379 redis:latest
